In [13]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1[1:5])

[2 3 4 5]


In [14]:
data = np.random.rand(2,3)
data

array([[0.44201419, 0.00823747, 0.84711659],
       [0.77963429, 0.19072397, 0.47561171]])

In [9]:
print(data.shape)
type(data)

(2, 3)

In [6]:
data2=np.array([[1,2,3,4],[5,6,7,8]])
data2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
data3=data2.reshape(-1)
data3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2[1,1:4])
print(arr2[0:2,0:4])

[6 7]
[[1 2 3]
 [5 6 7]]


In [14]:
arr3=np.array([1,2,3,4],dtype='S')
print(arr3)
print(type(arr3))

[b'1' b'2' b'3' b'4']
<class 'numpy.ndarray'>


In [17]:
arr4=np.array([1,2,3,4])
arr5=arr4.copy()
arr4[0]=45
print(arr4)
print(arr5)

[45  2  3  4]
[1 2 3 4]


In [18]:
arr4=np.array([1,2,3,4])
arr5=arr4.view()
arr4[0]=232
print(arr4)
print(arr5)

[232   2   3   4]
[232   2   3   4]


In [22]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [26]:
arr1=np.array([[1,2,3],[8,9,0]])
arr2=np.array([[4,5,6],[2,5,6]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 4 5 6]
 [8 9 0 2 5 6]]
